### ISSUE TITLE
Font awesome load time

### ISSUE THREAD

**Issue by dimdimich** [swissup/module-font-awesome#5]
One of clients suggested to consider speeding up font awesome load time https://stackoverflow.com/questions/35877994/font-awesome-is-loading-very-slow

What do you think?

**Comment by vovayatsyuk** [comment]
I don't see how this solution should speed up font loading. They take the same css and put it into the header with javascript instead of plain `<link>` tag.

p.s. We already load fontawesome styles from the local server merged with other styles.

**Comment by vovayatsyuk** [comment]
I'm closing it for now.
